version: '3.3'

services:
  restaurant:
    image: mysql
    restart: always
    environment:
      TZ: 'Asia/Bangkok'
      MYSQL_DATABASE: 'restaurant'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3306:3306'
#    volumes:
#        - ./db:/var/lib/mysql
